### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Masynchin** [bullbesh/reformer#2]
I want to have a really BADASS nickname, so I have typed:

~~~shell
~ Write your message here:

> ПУЛИ ОТ БАБУЛИ

TTYJlU OT 6A6YJlU
~~~

And I am not happy with the result. What about `--swag` option, that makes output nickname really SWAG?

**Comment by bullbesh** [comment]
What do you mean?

**Comment by Masynchin** [comment]
> What do you mean?

Something like `ღ☆Пɣλü☆Ӫҭ☆ϭȧбӱԉú☆ღ`, in addition to latin stars are added, or something like that. In one word - more SWAG.

**Comment by bullbesh** [comment]
> Something like `ღ☆Пɣλü☆Ӫҭ☆ϭȧбӱԉú☆ღ`, in addition to latin stars are added, or something like that. In one word - more SWAG.

I think it would be too much SWAG.

Initially, I planned that _reformer_ will work only with ASCII symbols. It becomes more practical for the user. Unfortunately, Your idea does not fit the idea of the project.

CTTACU6O 3A TTOHUMAHUE!
