### ISSUE TITLE
Lowercase

### ISSUE THREAD

**Issue by Masynchin** [bullbesh/reformer#4]
## Describe the bug

Lowercase cyrillic transforms to uppercase latin.

## Expected behavior

Lowercase cyrillic transforms to lowercase latin.

## Steps to reproduce

1) Run program.
2) Input `ЭтОт ТеКсТ СдЕлАн ЧеРеЗ РеФоРмЕр`
3) See that `ETOT TEKCT CDEJlAH 4EPE3 PEFOPMEP` output has no lowercase letters.

**Comment by bullbesh** [comment]
Initially I create two dictionaries. One of them was with uppercase symbols, another - with lowercase symbols. But when I start to create pairs I find that not everyone Cyrillic has correct Latin pair.

For example, I cant output Cyrillic "н" at lowercase, there is only Latin "H".

Thats isnt bug, its _output feature_. I want to program has only uppercase output.
